### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fahimalizain** [faztp12/stdout_reader#1]
- [ ] Port to C++ !!
- [ ] Support for more robust commandline args (specify encoding to listen on)
- [ ] Read the streams synchronously
- [ ] Support for std out error
- [ ] Make proper Readme.md
